################################
#      Tub's StatusPlugin      #
#          by TubYoub          #
################################
# Don't change this value, it's changed by the plugin if needed
fileversion: 4

# Check for updates on startup
# default: true
checkUpdate: true
# maximum Character length a Status should be allowed to have.
# default: 15
maxStatusLength: 15
# If the Chat formatter should be enabled (so the Plugin sends Messages with the Status in front of the Player name and formats colors).
# default: true
chatFormatter: true
# If the Tablist name should be changed by the plugin or not. (restart your server so the changes will work correctly)
# default: true
changeTablistNames: true
# Enable group mode for statuses
# When enabled, players can only choose from predefined status groups
# default: false
groupMode: false
# Define status groups
# Each group has a name and a status
statusGroups:
  t1:
    status: 'Team1'
  t2:
    status: 'Team2'
  t3:
    status: 'Team3'

# Opening and closing characters for the status
# default: '[' & ']'
openingCharacter: '['
closingCharacter: ']'