name: TubsStatusPlugin
version: '${project.version}'
main: de.tubyoub.statusplugin.StatusPlugin
api-version: 1.13
author: TubYoub
softdepend: [PlaceholderAPI, LuckPerms]
commands:
  status:
    description: Set a player's status, get info, get help, reload the plugin, set/reset max length
  group:
    description: Set a player's status group
permissions:
  StatusPlugin.setStatus:
    description: Allows setting own status. (default player)
    default: true
  StatusPlugin.group.set:
    description: Allows setting own status group. (default player)
    default: true
  StatusPlugin.admin.setStatus:
    description: Allows setting other players' statuses. (default op)
    default: op
  StatusPlugin.admin.reload:
    description: Allows reloading statuses. (default op)
    default: op
  StatusPlugin.admin.setMaxlength:
    description: Allows setting the maximum length of statuses.
    default: op
  StatusPlugin.admin.resetMaxlength:
    description: Allows resetting the maximum length of statuses to default.
    default: op
  StatusPlugin.formatting.color:
    description: Allows to use color in statuses
    default: op
  StatusPlugin.formatting.bold:
    description: Allows to use bold formatting in statuses
    default: op
  StatusPlugin.formatting.magic:
    description: Allows to use magic formatting in statuses
    default: op
  StatusPlugin.formatting.underline:
    description: Allows to use underline formatting in statuses
    default: op
  StatusPlugin.formatting.strikethrough:
    description: Allows to use strikethrough formatting in statuses
    default: op
  StatusPlugin.formatting.italic:
    description: Allows to use italic formatting in statuses
    default: op
  StatusPlugin.placeholders:
    description: Allows players to use Placeholders from PlaceholderAPI
    default: op